2024-05-28 10:44:18,756:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2024-05-28 10:44:18,760:INFO:discord.client: logging in using static token
2024-05-28 10:44:19,651:INFO:discord.gateway: Shard ID None has sent the IDENTIFY payload.
2024-05-28 10:44:20,097:INFO:discord.gateway: Shard ID None has connected to Gateway: ["gateway-prd-us-east1-d-fz0q",{"micros":143964,"calls":["id_created",{"micros":872,"calls":[]},"session_lookup_time",{"micros":9344,"calls":[]},"session_lookup_finished",{"micros":13,"calls":[]},"discord-sessions-prd-1-282",{"micros":132795,"calls":["start_session",{"micros":42831,"calls":["discord-api-rpc-799f6d64b-vd2wg",{"micros":33496,"calls":["get_user",{"micros":6481},"get_guilds",{"micros":2561},"send_scheduled_deletion_message",{"micros":6},"guild_join_requests",{"micros":864},"authorized_ip_coro",{"micros":6}]}]},"starting_guild_connect",{"micros":62,"calls":[]},"presence_started",{"micros":27884,"calls":[]},"guilds_started",{"micros":73,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":61893,"calls":[]},"connect_finished",{"micros":61898,"calls":[]},"build_ready",{"micros":42,"calls":[]},"clean_ready",{"micros":1,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: 957111350320df57c4648c2477768533).
2024-05-28 10:45:10,903:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 151, in <module>
    bot.run(os.environ.get('DISCORD_BOT_TOKEN'))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 81, in summarize
    images_file_api.append(genai.upload_file(path))
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/files.py", line 69, in upload_file
    response = client.create_file(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/client.py", line 77, in create_file
    result = request.execute()
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/http.py", line 1007, in next_chunk
    resp, content = _retry_request(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1724, in request
    (response, content) = self._request(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)

2024-05-28 10:45:20,903:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 151, in <module>
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 81, in summarize
    for webhook in webhooks:
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/files.py", line 69, in upload_file
    response = client.create_file(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/client.py", line 77, in create_file
    result = request.execute()
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/http.py", line 1084, in next_chunk
    resp, content = http.request(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1724, in request
    (response, content) = self._request(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)

2024-05-28 10:45:30,904:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 151, in <module>
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 81, in summarize
    for webhook in webhooks:
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/files.py", line 69, in upload_file
    response = client.create_file(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/client.py", line 77, in create_file
    result = request.execute()
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/http.py", line 902, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/googleapiclient/http.py", line 1084, in next_chunk
    resp, content = http.request(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1724, in request
    (response, content) = self._request(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/httplib2/__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)

2024-05-28 10:45:40,906:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 151, in <module>
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 95, in summarize
    async def thermalpaste(ctx):
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 812, in generate_content
    response = rpc(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1178, in __call__
    ) = self._blocking(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1162, in _blocking
    event = call.next_event()

2024-05-28 10:45:50,906:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 151, in <module>
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 95, in summarize
    async def thermalpaste(ctx):
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 812, in generate_content
    response = rpc(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1178, in __call__
    ) = self._blocking(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1162, in _blocking
    event = call.next_event()

2024-05-28 10:46:00,907:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 151, in <module>
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 95, in summarize
    async def thermalpaste(ctx):
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 812, in generate_content
    response = rpc(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1178, in __call__
    ) = self._blocking(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1162, in _blocking
    event = call.next_event()

2024-05-28 10:46:10,907:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 151, in <module>
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 95, in summarize
    async def thermalpaste(ctx):
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 812, in generate_content
    response = rpc(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1178, in __call__
    ) = self._blocking(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1162, in _blocking
    event = call.next_event()

2024-05-28 10:46:20,908:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 80 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 151, in <module>
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 104, in summarize
    await ctx.respond(f"pong! with a latency of {bot.latency * 1000}ms.")
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/files.py", line 93, in delete_file
    client.delete_file(request=request)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/file_service/client.py", line 1014, in delete_file
    rpc(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1178, in __call__
    ) = self._blocking(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1162, in _blocking
    event = call.next_event()

2024-05-28 10:46:20,962:INFO:discord.gateway: Timed out receiving packet. Attempting a reconnect.
2024-05-28 10:46:20,962:INFO:discord.client: Got a request to RESUME the websocket.
2024-05-28 10:46:21,447:INFO:discord.gateway: Shard ID None has sent the RESUME payload.
2024-05-28 10:46:21,749:INFO:discord.gateway: Shard ID None session has been invalidated.
2024-05-28 10:46:22,049:INFO:discord.client: Got a request to IDENTIFY the websocket.
2024-05-28 10:46:27,446:INFO:discord.gateway: Shard ID None has sent the IDENTIFY payload.
2024-05-28 10:46:27,929:INFO:discord.gateway: Shard ID None has connected to Gateway: ["gateway-prd-us-east1-c-3h93",{"micros":189748,"calls":["id_created",{"micros":1494,"calls":[]},"session_lookup_time",{"micros":6856,"calls":[]},"session_lookup_finished",{"micros":10,"calls":[]},"discord-sessions-prd-1-158",{"micros":178656,"calls":["start_session",{"micros":90988,"calls":["discord-api-pyupgrade-8f545c597-zcw58",{"micros":76891,"calls":["get_user",{"micros":11086},"get_guilds",{"micros":34717},"send_scheduled_deletion_message",{"micros":9},"guild_join_requests",{"micros":445},"authorized_ip_coro",{"micros":7}]}]},"starting_guild_connect",{"micros":52,"calls":[]},"presence_started",{"micros":164,"calls":[]},"guilds_started",{"micros":90,"calls":[]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":87313,"calls":[]},"connect_finished",{"micros":87318,"calls":[]},"build_ready",{"micros":16,"calls":[]},"clean_ready",{"micros":23,"calls":[]},"optimize_ready",{"micros":0,"calls":[]},"split_ready",{"micros":1,"calls":[]}]}]}] (Session ID: c9187015f4f4b5430b519a649cb2e32f).
2024-05-28 10:47:13,692:WARNING:discord.gateway: Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 151, in <module>
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 756, in run
    loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/client.py", line 400, in _run_event
    await coro(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1181, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 864, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/bot.py", line 1130, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 376, in invoke
    await injected(ctx)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/app.py", line 95, in summarize
    async def thermalpaste(ctx):
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/generativeai/generative_models.py", line 262, in generate_content
    response = self._client.generate_content(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py", line 812, in generate_content
    response = rpc(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1178, in __call__
    ) = self._blocking(
  File "/home/mithil/PycharmProjects/iph-discord-bot/env310/lib/python3.10/site-packages/grpc/_channel.py", line 1162, in _blocking
    event = call.next_event()

